name: Keep VELQA Alive
on:
  schedule:
    - cron: '*/15 * * * *' # Har 15 minute mein check karega
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server
        run: curl -I https://TERA-BACKEND-URL.b4a.run/health
